/**
 * PolicyEnforcerBaseService.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Nov 13, 2013 (09:13:21 GMT) WSDL2Java emitter.
 */

package it.csi.sigas.sigasbl.integration.iride;

public interface PolicyEnforcerBaseService extends java.rmi.Remote {
    public it.csi.sigas.sigasbl.integration.iride.Identita identificaUserPassword(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, it.csi.sigas.sigasbl.integration.iride.SystemException, it.csi.sigas.sigasbl.integration.iride.AuthException, it.csi.sigas.sigasbl.integration.iride.MalformedUsernameException, it.csi.sigas.sigasbl.integration.iride.IdProviderNotFoundException, it.csi.sigas.sigasbl.integration.iride.InternalException, it.csi.sigas.sigasbl.integration.iride.UnrecoverableException;
    public it.csi.sigas.sigasbl.integration.iride.Identita identificaCertificato(byte[] in0) throws java.rmi.RemoteException, it.csi.sigas.sigasbl.integration.iride.SystemException, it.csi.sigas.sigasbl.integration.iride.CertRevokedException, it.csi.sigas.sigasbl.integration.iride.IdProviderNotFoundException, it.csi.sigas.sigasbl.integration.iride.InternalException, it.csi.sigas.sigasbl.integration.iride.CertOutsideValidityException, it.csi.sigas.sigasbl.integration.iride.UnrecoverableException;
    public it.csi.sigas.sigasbl.integration.iride.Identita identificaUserPasswordPIN(java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, it.csi.sigas.sigasbl.integration.iride.SystemException, it.csi.sigas.sigasbl.integration.iride.AuthException, it.csi.sigas.sigasbl.integration.iride.MalformedUsernameException, it.csi.sigas.sigasbl.integration.iride.IdProviderNotFoundException, it.csi.sigas.sigasbl.integration.iride.InternalException, it.csi.sigas.sigasbl.integration.iride.UnrecoverableException;
    public boolean isPersonaAutorizzataInUseCase(it.csi.sigas.sigasbl.integration.iride.Identita in0, it.csi.sigas.sigasbl.integration.iride.UseCase in1) throws java.rmi.RemoteException, it.csi.sigas.sigasbl.integration.iride.SystemException, it.csi.sigas.sigasbl.integration.iride.NoSuchUseCaseException, it.csi.sigas.sigasbl.integration.iride.NoSuchApplicationException, it.csi.sigas.sigasbl.integration.iride.IdentitaNonAutenticaException, it.csi.sigas.sigasbl.integration.iride.InternalException, it.csi.sigas.sigasbl.integration.iride.UnrecoverableException;
    public it.csi.sigas.sigasbl.integration.iride.UseCase[] findUseCasesForPersonaInApplication(it.csi.sigas.sigasbl.integration.iride.Identita in0, it.csi.sigas.sigasbl.integration.iride.Application in1) throws java.rmi.RemoteException, it.csi.sigas.sigasbl.integration.iride.SystemException, it.csi.sigas.sigasbl.integration.iride.NoSuchApplicationException, it.csi.sigas.sigasbl.integration.iride.IdentitaNonAutenticaException, it.csi.sigas.sigasbl.integration.iride.InternalException, it.csi.sigas.sigasbl.integration.iride.UnrecoverableException;
    public boolean isIdentitaAutentica(it.csi.sigas.sigasbl.integration.iride.Identita in0) throws java.rmi.RemoteException, it.csi.sigas.sigasbl.integration.iride.SystemException, it.csi.sigas.sigasbl.integration.iride.InternalException, it.csi.sigas.sigasbl.integration.iride.UnrecoverableException;
    public java.lang.String getInfoPersonaInUseCase(it.csi.sigas.sigasbl.integration.iride.Identita in0, it.csi.sigas.sigasbl.integration.iride.UseCase in1) throws java.rmi.RemoteException, it.csi.sigas.sigasbl.integration.iride.SystemException, it.csi.sigas.sigasbl.integration.iride.NoSuchUseCaseException, it.csi.sigas.sigasbl.integration.iride.NoSuchApplicationException, it.csi.sigas.sigasbl.integration.iride.IdentitaNonAutenticaException, it.csi.sigas.sigasbl.integration.iride.InternalException, it.csi.sigas.sigasbl.integration.iride.UnrecoverableException;
    public it.csi.sigas.sigasbl.integration.iride.Ruolo[] findRuoliForPersonaInUseCase(it.csi.sigas.sigasbl.integration.iride.Identita in0, it.csi.sigas.sigasbl.integration.iride.UseCase in1) throws java.rmi.RemoteException, it.csi.sigas.sigasbl.integration.iride.SystemException, it.csi.sigas.sigasbl.integration.iride.NoSuchUseCaseException, it.csi.sigas.sigasbl.integration.iride.NoSuchApplicationException, it.csi.sigas.sigasbl.integration.iride.IdentitaNonAutenticaException, it.csi.sigas.sigasbl.integration.iride.InternalException, it.csi.sigas.sigasbl.integration.iride.UnrecoverableException;
    public it.csi.sigas.sigasbl.integration.iride.Ruolo[] findRuoliForPersonaInApplication(it.csi.sigas.sigasbl.integration.iride.Identita in0, it.csi.sigas.sigasbl.integration.iride.Application in1) throws java.rmi.RemoteException, it.csi.sigas.sigasbl.integration.iride.SystemException, it.csi.sigas.sigasbl.integration.iride.NoSuchApplicationException, it.csi.sigas.sigasbl.integration.iride.IdentitaNonAutenticaException, it.csi.sigas.sigasbl.integration.iride.InternalException, it.csi.sigas.sigasbl.integration.iride.UnrecoverableException;
    public java.lang.String getInfoPersonaSchema(it.csi.sigas.sigasbl.integration.iride.Ruolo in0) throws java.rmi.RemoteException, it.csi.sigas.sigasbl.integration.iride.SystemException, it.csi.sigas.sigasbl.integration.iride.BadRuoloException, it.csi.sigas.sigasbl.integration.iride.InternalException, it.csi.sigas.sigasbl.integration.iride.UnrecoverableException;
    public it.csi.sigas.sigasbl.integration.iride.Actor[] findActorsForPersonaInApplication(it.csi.sigas.sigasbl.integration.iride.Identita in0, it.csi.sigas.sigasbl.integration.iride.Application in1) throws java.rmi.RemoteException, it.csi.sigas.sigasbl.integration.iride.SystemException, it.csi.sigas.sigasbl.integration.iride.NoSuchApplicationException, it.csi.sigas.sigasbl.integration.iride.IdentitaNonAutenticaException, it.csi.sigas.sigasbl.integration.iride.InternalException, it.csi.sigas.sigasbl.integration.iride.UnrecoverableException;
    public it.csi.sigas.sigasbl.integration.iride.Actor[] findActorsForPersonaInUseCase(it.csi.sigas.sigasbl.integration.iride.Identita in0, it.csi.sigas.sigasbl.integration.iride.UseCase in1) throws java.rmi.RemoteException, it.csi.sigas.sigasbl.integration.iride.SystemException, it.csi.sigas.sigasbl.integration.iride.NoSuchUseCaseException, it.csi.sigas.sigasbl.integration.iride.NoSuchApplicationException, it.csi.sigas.sigasbl.integration.iride.IdentitaNonAutenticaException, it.csi.sigas.sigasbl.integration.iride.InternalException, it.csi.sigas.sigasbl.integration.iride.UnrecoverableException;
    public boolean isPersonaInRuolo(it.csi.sigas.sigasbl.integration.iride.Identita in0, it.csi.sigas.sigasbl.integration.iride.Ruolo in1) throws java.rmi.RemoteException, it.csi.sigas.sigasbl.integration.iride.SystemException, it.csi.sigas.sigasbl.integration.iride.BadRuoloException, it.csi.sigas.sigasbl.integration.iride.IdentitaNonAutenticaException, it.csi.sigas.sigasbl.integration.iride.InternalException, it.csi.sigas.sigasbl.integration.iride.UnrecoverableException;
}
