package it.csi.sigas.sigasbl.integration.epay.from.enti2epaywsosrv;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.7.14.redhat-1
 * 2020-11-16T12:14:42.064+01:00
 * Generated source version: 2.7.14.redhat-1
 * 
 */
@WebServiceClient(name = "Enti2EPaywsoService", 
                  wsdlLocation = "file:./wsdl/Enti2EPaywsoService.wsdl",
//                wsdlLocation = "classpath:./wsdl/Enti2EPaywsoService.wsdl",
                  targetNamespace = "http://www.csi.it/epay/epaywso/enti2epaywsosrv") 
public class Enti2EPaywsoService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.csi.it/epay/epaywso/enti2epaywsosrv", "Enti2EPaywsoService");
    public final static QName Enti2EPaywsoServiceSOAP = new QName("http://www.csi.it/epay/epaywso/enti2epaywsosrv", "Enti2EPaywsoServiceSOAP");
    static {
    	/*
        URL url = null;
        try {
            url = new URL("file:./wsdl/Enti2EPaywsoService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Enti2EPaywsoService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/MyProjects/workspace-sigas/_DOCS/_refs/Specifiche%20Integrazione-v2.8/Enti2EPaywsoService.wsdl");
        }
        WSDL_LOCATION = url;
        */
    	
        WSDL_LOCATION = Enti2EPaywsoService_Service.class.getResource("/META-INF/wsdl/Enti2EPaywsoService.wsdl");
    }

    public Enti2EPaywsoService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Enti2EPaywsoService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Enti2EPaywsoService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Enti2EPaywsoService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Enti2EPaywsoService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Enti2EPaywsoService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns Enti2EPaywsoService
     */
    @WebEndpoint(name = "Enti2EPaywsoServiceSOAP")
    public Enti2EPaywsoService getEnti2EPaywsoServiceSOAP() {
        return super.getPort(Enti2EPaywsoServiceSOAP, Enti2EPaywsoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Enti2EPaywsoService
     */
    @WebEndpoint(name = "Enti2EPaywsoServiceSOAP")
    public Enti2EPaywsoService getEnti2EPaywsoServiceSOAP(WebServiceFeature... features) {
        return super.getPort(Enti2EPaywsoServiceSOAP, Enti2EPaywsoService.class, features);
    }

}
