package it.csi.sigas.sigasbl.integration.epay.from.enti2epaywsosrv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.14.redhat-1
 * 2020-11-16T12:14:42.038+01:00
 * Generated source version: 2.7.14.redhat-1
 * 
 */
@WebService(targetNamespace = "http://www.csi.it/epay/epaywso/enti2epaywsosrv", name = "Enti2EPaywsoService")
@XmlSeeAlso({it.csi.sigas.sigasbl.integration.epay.from.clienttypes.ObjectFactory.class, it.csi.sigas.sigasbl.integration.epay.from.enti2epaywso.types.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Enti2EPaywsoService {

    @WebMethod(operationName = "AggiornaPosizioniDebitorie", action = "http://www.csi.it/epay/epaywso/service/AggiornaPosizioniDebitorie")
    @WebResult(name = "EPaywsoServiceResponse", targetNamespace = "http://www.csi.it/epay/epaywso/types", partName = "parameters")
    public it.csi.sigas.sigasbl.integration.epay.from.clienttypes.ResponseType aggiornaPosizioniDebitorie(
        @WebParam(partName = "parameters", name = "AggiornaPosizioniDebitorieRequest", targetNamespace = "http://www.csi.it/epay/epaywso/enti2epaywso/types")
        it.csi.sigas.sigasbl.integration.epay.from.enti2epaywso.types.AggiornaPosizioniDebitorieRequest parameters
    );

    @WebMethod(operationName = "InserisciListaDiCarico", action = "http://www.csi.it/epay/epaywso/service/InserisciListaDiCarico")
    @WebResult(name = "EPaywsoServiceResponse", targetNamespace = "http://www.csi.it/epay/epaywso/types", partName = "parameters")
    public it.csi.sigas.sigasbl.integration.epay.from.clienttypes.ResponseType inserisciListaDiCarico(
        @WebParam(partName = "parameters", name = "InserisciListaDiCaricoRequest", targetNamespace = "http://www.csi.it/epay/epaywso/enti2epaywso/types")
        it.csi.sigas.sigasbl.integration.epay.from.enti2epaywso.types.InserisciListaDiCaricoRequest parameters
    );
}
