INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (0, '000', '', '', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (1, '001', 'TORINO', 'TO', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (2, '002', 'VERCELLI', 'VC', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (3, '003', 'NOVARA', 'NO', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (4, '004', 'CUNEO', 'CN', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (5, '005', 'ASTI', 'AT', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (6, '006', 'ALESSANDRIA', 'AL', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (7, '007', 'VALLE D''AOSTA/VALLÉE D''AOSTE', 'AO', '2008-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (8, '008', 'IMPERIA', 'IM', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (9, '009', 'SAVONA', 'SV', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (10, '010', 'GENOVA', 'GE', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (11, '011', 'LA SPEZIA', 'SP', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (12, '012', 'VARESE', 'VA', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (13, '013', 'COMO', 'CO', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (14, '014', 'SONDRIO', 'SO', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (15, '015', 'MILANO', 'MI', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (16, '016', 'BERGAMO', 'BG', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (17, '017', 'BRESCIA', 'BS', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (18, '018', 'PAVIA', 'PV', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (19, '019', 'CREMONA', 'CR', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (20, '020', 'MANTOVA', 'MN', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (21, '021', 'BOLZANO/BOZEN', 'BZ', '2008-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (22, '022', 'TRENTO', 'TN', '1920-10-16', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (23, '023', 'VERONA', 'VR', '1866-11-19', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (24, '024', 'VICENZA', 'VI', '1866-11-19', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (25, '025', 'BELLUNO', 'BL', '1866-11-19', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (26, '026', 'TREVISO', 'TV', '1866-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (27, '027', 'VENEZIA', 'VE', '1866-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (28, '028', 'PADOVA', 'PD', '1866-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (29, '029', 'ROVIGO', 'RO', '1866-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (30, '030', 'UDINE', 'UD', '1866-11-19', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (31, '031', 'GORIZIA', 'GO', '1921-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (32, '032', 'TRIESTE', 'TS', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (33, '033', 'PIACENZA', 'PC', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (34, '034', 'PARMA', 'PR', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (35, '035', 'REGGIO NELL''EMILIA', 'RE', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (36, '036', 'MODENA', 'MO', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (37, '037', 'BOLOGNA', 'BO', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (38, '038', 'FERRARA', 'FE', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (39, '039', 'RAVENNA', 'RA', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (40, '040', 'FORLI''-CESENA', 'FC', '1992-04-04', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (41, '041', 'PESARO E URBINO', 'PU', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (42, '042', 'ANCONA', 'AN', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (43, '043', 'MACERATA', 'MC', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (44, '044', 'ASCOLI PICENO', 'AP', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (45, '045', 'MASSA-CARRARA', 'MS', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (46, '046', 'LUCCA', 'LU', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (47, '047', 'PISTOIA', 'PT', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (48, '048', 'FIRENZE', 'FI', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (49, '049', 'LIVORNO', 'LI', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (50, '050', 'PISA', 'PI', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (51, '051', 'AREZZO', 'AR', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (52, '052', 'SIENA', 'SI', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (53, '053', 'GROSSETO', 'GR', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (54, '054', 'PERUGIA', 'PG', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (55, '055', 'TERNI', 'TR', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (56, '056', 'VITERBO', 'VT', '1871-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (57, '057', 'RIETI', 'RI', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (58, '058', 'ROMA', 'RM', '1871-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (59, '059', 'LATINA', 'LT', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (60, '060', 'FROSINONE', 'FR', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (61, '061', 'CASERTA', 'CE', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (62, '062', 'BENEVENTO', 'BN', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (63, '063', 'NAPOLI', 'NA', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (64, '064', 'AVELLINO', 'AV', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (65, '065', 'SALERNO', 'SA', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (66, '066', 'L''AQUILA', 'AQ', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (67, '067', 'TERAMO', 'TE', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (68, '068', 'PESCARA', 'PE', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (69, '069', 'CHIETI', 'CH', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (70, '070', 'CAMPOBASSO', 'CB', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (71, '071', 'FOGGIA', 'FG', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (72, '072', 'BARI', 'BA', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (73, '073', 'TARANTO', 'TA', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (74, '074', 'BRINDISI', 'BR', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (75, '075', 'LECCE', 'LE', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (76, '076', 'POTENZA', 'PZ', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (77, '077', 'MATERA', 'MT', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (78, '078', 'COSENZA', 'CS', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (79, '079', 'CATANZARO', 'CZ', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (80, '080', 'REGGIO DI CALABRIA', 'RC', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (81, '081', 'TRAPANI', 'TP', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (82, '082', 'PALERMO', 'PA', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (83, '083', 'MESSINA', 'ME', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (84, '084', 'AGRIGENTO', 'AG', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (85, '085', 'CALTANISSETTA', 'CL', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (86, '086', 'ENNA', 'EN', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (87, '087', 'CATANIA', 'CT', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (88, '088', 'RAGUSA', 'RG', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (89, '089', 'SIRACUSA', 'SR', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (90, '090', 'SASSARI', 'SS', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (91, '091', 'NUORO', 'NU', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (92, '092', 'CAGLIARI', 'CA', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (93, '093', 'PORDENONE', 'PN', '1866-11-19', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (94, '094', 'ISERNIA', 'IS', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (95, '095', 'ORISTANO', 'OR', '1861-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (96, '096', 'BIELLA', 'BI', '1992-04-16', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (97, '097', 'LECCO', 'LC', '1992-04-16', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (98, '098', 'LODI', 'LO', '1992-04-16', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (99, '099', 'RIMINI', 'RN', '1992-04-16', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (100, '100', 'PRATO', 'PO', '1992-04-16', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (101, '101', 'CROTONE', 'KR', '1992-04-16', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (102, '102', 'VIBO VALENTIA', 'VV', '1992-04-16', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (103, '103', 'VERBANO-CUSIO-OSSOLA', 'VB', '1992-05-23', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (104, '108', 'MONZA E DELLA BRIANZA', 'MB', '2009-06-30', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (105, '109', 'FERMO', 'FM', '2009-06-30', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (106, '110', 'BARLETTA-ANDRIA-TRANI', 'BT', '2009-06-30', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (107, '111', 'SUD SARDEGNA', 'SU', '2018-01-01', null);
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (108, '111', 'SUD SARDEGNA', 'XX', '2017-01-01', '2017-12-31');
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (109, '104', 'OLBIA-TEMPIO', 'OT', '1996-01-24', '2016-12-31');
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (110, '105', 'OGLIASTRA', 'OG', '2006-01-01', '2016-12-31');
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (111, '106', 'MEDIO CAMPIDANO', 'VS', '2006-01-01', '2016-12-31');
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (112, '107', 'CARBONIA-IGLESIAS', 'CI', '2006-01-01', '2016-12-31');
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (113, '007', 'VALLE D''AOSTA', 'AO', '1861-01-01', '2007-12-31');
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (114, '021', 'BOLZANO - BOZEN', 'BZ', '1921-01-01', '2007-12-31');
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (115, '040', 'FORLI''', 'FO', '1861-01-01', '1992-04-03');
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (116, '701', 'FIUME', 'FM', '1921-01-01', '1950-12-31');
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (117, '702', 'POLA', 'PL', '1921-01-01', '1950-12-31');
INSERT INTO sigas_provincia (id_provincia, cod_istat_provincia, denom_provincia, sigla_provincia, inizio_validita, fine_validita) VALUES (118, '703', 'ZARA', 'ZA', '1921-01-01', '1950-12-31');