package it.csi.sigas.sigasbl.integration.epay.from.epaywso2entisrv;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.14.redhat-1
 * 2020-11-13T13:15:44.450+01:00
 * Generated source version: 2.7.14.redhat-1
 * 
 */
@WebServiceClient(name = "EPaywso2EntiService", 
                  wsdlLocation = "file:/C:/MyProjects/workspace-sigas/sigasbl/conf/web/sigas/rest/wsdl/EPaywso2EntiServiceSOAP.wsdl",
                  targetNamespace = "http://www.csi.it/epay/epaywso/epaywso2entisrv") 
public class EPaywso2EntiService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.csi.it/epay/epaywso/epaywso2entisrv", "EPaywso2EntiService");
    public final static QName EPaywso2EntiServiceSOAP = new QName("http://www.csi.it/epay/epaywso/epaywso2entisrv", "EPaywso2EntiServiceSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/MyProjects/workspace-sigas/sigasbl/conf/web/sigas/rest/wsdl/EPaywso2EntiServiceSOAP.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EPaywso2EntiService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/MyProjects/workspace-sigas/sigasbl/conf/web/sigas/rest/wsdl/EPaywso2EntiServiceSOAP.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EPaywso2EntiService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EPaywso2EntiService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EPaywso2EntiService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EPaywso2EntiService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EPaywso2EntiService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EPaywso2EntiService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns EPaywso2EntiService
     */
    @WebEndpoint(name = "EPaywso2EntiServiceSOAP")
    public EPaywso2EntiService getEPaywso2EntiServiceSOAP() {
        return super.getPort(EPaywso2EntiServiceSOAP, EPaywso2EntiService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EPaywso2EntiService
     */
    @WebEndpoint(name = "EPaywso2EntiServiceSOAP")
    public EPaywso2EntiService getEPaywso2EntiServiceSOAP(WebServiceFeature... features) {
        return super.getPort(EPaywso2EntiServiceSOAP, EPaywso2EntiService.class, features);
    }

}
