package it.csi.sigas.sigasbl.integration.epay.from.epaywso2entisrv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.14.redhat-1
 * 2020-11-13T13:15:44.418+01:00
 * Generated source version: 2.7.14.redhat-1
 * 
 */
@WebService(targetNamespace = "http://www.csi.it/epay/epaywso/epaywso2entisrv", name = "EPaywso2EntiService")
@XmlSeeAlso({it.csi.sigas.sigasbl.integration.epay.from.types.ObjectFactory.class, it.csi.sigas.sigasbl.integration.epay.from.epaywso2enti.types.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface EPaywso2EntiService {

    @WebMethod(operationName = "EsitoInserimentoListaDiCarico", action = "http://www.csi.it/epay/epaywso/service/EsitoInserimentoListaDiCarico")
    @WebResult(name = "EPaywsoServiceResponse", targetNamespace = "http://www.csi.it/epay/epaywso/types", partName = "parameters")
    public it.csi.sigas.sigasbl.integration.epay.from.types.ResponseType esitoInserimentoListaDiCarico(
        @WebParam(partName = "parameters", name = "EsitoInserimentoListaDiCaricoRequest", targetNamespace = "http://www.csi.it/epay/epaywso/epaywso2enti/types")
        it.csi.sigas.sigasbl.integration.epay.from.epaywso2enti.types.EsitoInserimentoListaDiCaricoRequest parameters
    );

    @WebMethod(operationName = "EsitoAggiornaPosizioniDebitorie", action = "http://www.csi.it/epay/epaywso/service/EsitoAggiornaPosizioniDebitorie")
    @WebResult(name = "EPaywsoServiceResponse", targetNamespace = "http://www.csi.it/epay/epaywso/types", partName = "parameters")
    public it.csi.sigas.sigasbl.integration.epay.from.types.ResponseType esitoAggiornaPosizioniDebitorie(
        @WebParam(partName = "parameters", name = "EsitoAggiornaPosizioniDebitorieRequest", targetNamespace = "http://www.csi.it/epay/epaywso/epaywso2enti/types")
        it.csi.sigas.sigasbl.integration.epay.from.epaywso2enti.types.EsitoAggiornaPosizioniDebitorieRequest parameters
    );

    @WebMethod(operationName = "TrasmettiRichiesteDiRevoca", action = "http://www.csi.it/epay/epaywso/service/TrasmettiRichiesteDiRevoca")
    @WebResult(name = "EPaywsoServiceResponse", targetNamespace = "http://www.csi.it/epay/epaywso/types", partName = "parameters")
    public it.csi.sigas.sigasbl.integration.epay.from.types.ResponseType trasmettiRichiesteDiRevoca(
        @WebParam(partName = "parameters", name = "TrasmettiRichiesteDiRevocaRequest", targetNamespace = "http://www.csi.it/epay/epaywso/epaywso2enti/types")
        it.csi.sigas.sigasbl.integration.epay.from.epaywso2enti.types.TrasmettiRichiesteDiRevocaRequest parameters
    );

    @WebMethod(operationName = "TrasmettiRT", action = "http://www.csi.it/epay/epaywso/service/TrasmettiRT")
    @WebResult(name = "EPaywsoServiceResponse", targetNamespace = "http://www.csi.it/epay/epaywso/types", partName = "parameters")
    public it.csi.sigas.sigasbl.integration.epay.from.types.ResponseType trasmettiRT(
        @WebParam(partName = "parameters", name = "TrasmettiRTRequest", targetNamespace = "http://www.csi.it/epay/epaywso/epaywso2enti/types")
        it.csi.sigas.sigasbl.integration.epay.from.epaywso2enti.types.TrasmettiRTRequest parameters
    );

    @WebMethod(operationName = "TrasmettiNotifichePagamento", action = "http://www.csi.it/epay/epaywso/service/TrasmettiNotifichePagamento")
    @WebResult(name = "EPaywsoServiceResponse", targetNamespace = "http://www.csi.it/epay/epaywso/types", partName = "parameters")
    public it.csi.sigas.sigasbl.integration.epay.from.types.ResponseType trasmettiNotifichePagamento(
        @WebParam(partName = "parameters", name = "TrasmettiNotifichePagamentoRequest", targetNamespace = "http://www.csi.it/epay/epaywso/epaywso2enti/types")
        it.csi.sigas.sigasbl.integration.epay.from.epaywso2enti.types.TrasmettiNotifichePagamentoRequest parameters
    );

    @WebMethod(operationName = "TrasmettiAvvisiScaduti", action = "http://www.csi.it/epay/epaywso/service/TrasmettiAvvisiScaduti")
    @WebResult(name = "EPaywsoServiceResponse", targetNamespace = "http://www.csi.it/epay/epaywso/types", partName = "parameters")
    public it.csi.sigas.sigasbl.integration.epay.from.types.ResponseType trasmettiAvvisiScaduti(
        @WebParam(partName = "parameters", name = "TrasmettiAvvisiScadutiRequest", targetNamespace = "http://www.csi.it/epay/epaywso/epaywso2enti/types")
        it.csi.sigas.sigasbl.integration.epay.from.epaywso2enti.types.TrasmettiAvvisiScadutiRequest parameters
    );
}
